---
title: "MakeFile"
output: pdf_document
header-includes:
- \usepackage{float}
- \usepackage{hyperref}
- \hypersetup{
     colorlinks=true,
     linkcolor=black,
     citecolor = black,
     urlcolor=blue,
     }
fontsize: 12pt
---

# ¿Qué es un Makefile?

Un Makefile es un archivo para compilar código. Tenemos Makefiles para cada tarea que creamos en nuestro análisis de datos. Se guardan dentro de una tarea pero fuera de los subdirectorios (input, output, src, hand, frozen).

# ¿Cómo debe ser un Makefile?

1. Como cualquier archivo de texto que creamos, siempre debe incluir una cabecera que incluye:

Author (autor/a): 
Maintainers (mantenedores):
Date (fecha): Oct. 16 2019
License (licencia): 
 ------
ruta/del/archivo

2. Después, hay que seguir esta estructura:

2.1 Para ejecutar scripts escritos en R:
```
.PHONY: all clean
 
all:  ruta(s) de los archivos de salida
 
clean:
	rm output/*
 
ruta del primer archivo de salida: \
		script para crear ese archivo 
	Rscript --vanilla $<
 
ruta del segundo archivo de salida: \
		script para crear ese archivo 
	Rscript --vanilla $<
```

3. Ejemplo

Digamos que queremos crear un Makefile para la tarea "append" (añadir) en un análisis de datos sobre los asesinatos de líderes sociales en Colombia. El archivo de salida será una base de datos con todos los años que tenemos en nuestros registros. También crearemos un archivo .log con información básica que usaremos después para nuestro informe.
```
Author: VRA
Maintainers: VRA, PB, CAF
Date: Oct. 16 2019
License: GPL-2 or newer
------
CO-leaders/append/Makefile

.PHONY: all clean

all: output/allyears.rds \
	output/logfileappend.log

clean:
	rm output/*

output/allyears.rds: \
		src/appendyears.R 
	cd ../clean && make
	Rscript --vanilla $<

output/logfileappend.log: \
		src/appendyears.R
	cd ../clean && make
	Rscript --vanilla $<

done
```

<!-- done -->

