---
title: "Some thoughts on replicability"
output: pdf_document
header-includes:
- \usepackage{float}
- \usepackage{hyperref}
- \hypersetup{
     colorlinks=true,
     linkcolor=black,
     citecolor = black,
     urlcolor=blue,
     }
fontsize: 12pt
---

# Why being able to audit things is important? 

Being able to replicate the results that we get by analyzing data is key for our reputation. In general, being able to replicate something means that one can get the same result over and over again using the same input data and script. In science we also talk about *reproducibility*, which involves more experimental variation. Reproducibility/replicabilite are one best practice in science and is one of the reasons for not using the program environvenments, such as R studio but in the command line. 

When we have replicable results we can share our methods with other scientist, which creates two positive externalities. On the one hand, our results can be validated by other researchers, giving credibility to them. On the other hand, we can share our methods with other researchers, leading to scale economies and preventing duplications efforts.

The world is facing a reproducibility crisis. Nature magazine conducted [a survey](https://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970) on this topic and found that "more than 70% of researchers have tried and failed to reproduce another scientist's experiments, and more than half have failed to reproduce their own experiments".

Although this crisis is faced by many fields, working in human rights gives an extra pressure on the importance of replicability. Even though our methods and results are unbiased and we do not manipulate any step of the process for getting the truth, it is very likely that our findings will be not liked by different actors. Therefore, when we publish our results and human rights adcovates use them, we need to be sure that the results have no mistakes. Guaranteeing replicability is key for this. 

# Some readings

You can click [here](http://ropensci.github.io/reproducibility-guide/sections/references/) for some readings on reproducible results. 



<!-- done -->

